####CONFIG_0001####
photo_path: "/storage/uav/photosets/sample_rgb_photoset_01"
multispectral: False
buildDenseCloud: # (Metashape: buildDepthMaps, buildDenseCloud, classifyGroundPoints, and exportPoints)
    enabled: False

####CONFIG_0002####
photo_path: "/storage/uav/photosets/sample_rgb_photoset_02"
multispectral: True

####CONFIG_0003####
photo_path: "/storage/uav/photosets/sample_rgb_photoset_03"
multispectral: False
